name: Run Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Run Go Tests

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [1.22.3]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
          check-latest: true
          cache: true

      - name: Run Tests
        run: go test -v ./...
